version: "3.10"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webqa-agent:latest
    container_name: webqa-agent
    volumes:
      # 挂载配置文件
      - ./config:/app/config:ro
      # 挂载日志目录
      - ./logs:/app/logs
      # 挂载测试结果目录
      - ./reports:/app/reports
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} #优先使用环境变量
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=true  # 标识Docker环境，强制headless模式
    restart: "no"    # 开发模式不自动重启，便于调试
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
